environment:

  global:
      PYTHON: "C:\\conda"
      PYTHON_ARCH: "64"

  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python36-x64"
      CONDA_DEPENDENCIES: "pyyaml qt=5 pyqt=5"
      PIP_DEPENDENCIES: "appdirs pyinstaller"

platform:
  -x64

install:
  # Install conda using ci-helpers. More information about ci-helpers can
  # be found here: https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "rm ci-helpers/test_env.py"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Switch to test environment
  - "activate test"

  # Check that we have the expected version and architecture for Python
  - "python --version"

build_script:
  - cmd: >-
    pyinstaller hugo-gui.spec

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist

deploy: off
#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
